### ISSUE TITLE
InputReportReasonSpam

### ISSUE THREAD

**Issue by IBokiy** [NoImN0t/TG-AutoReport#3]
Привіт.

Питання: `peer: InputPeerChannel = await client.resolve_peer(i)
            response = await client.send(data=ReportPeer(peer=peer, reason=InputReportReasonSpam(), message="Тероризм"))`
ціль - спам, але далі є еще комментар, але, якщо руками відпрацювати в телеграм, то пісня нажимання "спам" немає коментаря. Бачив що в локументації до бібліотеки є "Інше", після якого якраз можна писати комментар. Чи можу я змінити [InputReportReasonSpam] на [InputReportReasonOther]?

**Comment by NoImN0t** [comment]
Так звісно. Можете зробити Pull Request зі змінами в коді.

**Comment by IBokiy** [comment]
Дякую. Не став чекати відповідь і змінив - відпрацювало і за 2 дні наче питань більше не виникало.
