### ISSUE TITLE
зі вчорашнього вечора видає одну й ту саму помилку

### ISSUE THREAD

**Issue by antlicker** [NoImN0t/TG-AutoReport#5]
https://ibb.co/sw9K2sN

**Comment by slavaGanzin** [comment]
Там же написано: ждите из-за большого количества сообщений. Телеграм под большой нагрузкой, я даже зарегистрировать новый аккаунт не могу

**Comment by NoImN0t** [comment]
![image](https://user-images.githubusercontent.com/100516013/157435082-07bca8ae-c04e-429a-8d8f-19b09b3c7d03.png)
Ви досягнули ліміт методу `ResolveUsername`

По публічним даним - цей метод можна використовувати до 40 разів на добу.
